<?php

/**
 * @file
 * Functions to support theming.
 */

require_once dirname(__FILE__) . '/includes/nodes.inc';
require_once dirname(__FILE__) . '/includes/blocks.inc';
require_once dirname(__FILE__) . '/includes/taxonomies.inc';
require_once dirname(__FILE__) . '/includes/paragraphs.inc';
require_once dirname(__FILE__) . '/includes/views.inc';
require_once dirname(__FILE__) . '/includes/user.inc';
