name: nombre_proyecto
recipe: drupal10
config:
  webroot: web
  php: 8.1
  composer_version: 2-latest
  via: apache
  database: mysql:5.7.38
  config:
    php: config/php.ini
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'https://nombre_proyecto.lndo.site'
        PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -S mailhog:1025'
  mailhog:
      type: mailhog
      portforward: true
      hogfrom:
        - appserver
tooling:
  drush:
    cmd: /app/vendor/drush/drush/drush
proxy:
  mailhog:
    - mail.lndo.site
